The final part of my Best portfolio
posh101/My-Portfolio pull request #3
Opened 2022-10-29 10:19 UTC by posh101

- Add linters
- Add README 
- Add header to HTML
- Add 5 navigation buttons.
- Add a background image
- Add a new font family.
- Add styles to the html.

2022-10-29 11:19 UTC, Yazino12 requested changes
## Hi @posh101🖐🏾,

You've done well implementing most of the project requirements 🎉, but there are still some changes you need to make before moving on to the next project 🔨.

### To highlight:
- Professional readme file ✔️ 
- Linters are passing ✔️ 

# STATUS: REQUIRED CHANGES ♻♻♻
![ALMOST](https://media.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif)
_Check the comments under the review 👇🏽👇🏽👇🏽._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @Yazino12 when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 11:19 UTC, Yazino12 commented on index.html
> +        <br>
- **[OPTIONAL]** I see that you are using `<br>` tags to make the space between your sections. To make your code clean try styling your section margins, that way you are cleaning up these repeated lines of the same tag and it will make your code much cleaner 🧹👊🏽.

2022-10-29 11:19 UTC, Yazino12 commented on index.html
> +
- [ ] Your projects section doesn't have the title **My Recent Works**. Please add the title as you can see below your design has the title and your project doesn't 👇🏽.
- [ ] As in the design template the background of your card has a grayish color. Kindly change the background to white 👍🏽.

- **Your project**
![image](https://user-images.githubusercontent.com/43172164/198827205-17e90576-9767-4b8e-952a-09484738cc69.png)

- **The design**
![image](https://user-images.githubusercontent.com/43172164/198827221-2e6e6b2e-af3b-497d-ae61-6a6289fc9bc3.png)

2022-10-29 11:19 UTC, Yazino12 commented on index.html
> +        <button class="button4" type="Ruby">Ruby</button>
- [ ] For semantic correctness. HTML has the ability to express lists of things, and it helps the Google robot 🤖, screen readers, and all manner of users who don't care solely about the presentation of the site understand your content better. For this reason, consider using `li` nested with `ul` tags. So you end with something like this 👇🏽: 

![image](https://user-images.githubusercontent.com/43172164/198827727-f621e468-0cb6-4f3e-a633-ff09ae20951d.png)

2022-10-29 11:19 UTC, Yazino12 commented on index.html
> +        <button class="button5" type="See Project">See Project</button>
- [ ] Having elements that load quickly while displaying a simple interface, consider adding button styling: Active, Hover, and Pressed to your button ✨. [see design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

2022-10-29 11:19 UTC, Yazino12 commented on index.html
>  </html>
- [ ] As in the [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md) you were expected to implement two sections: **The projects** section which you implemented ✔ and the **About myself** section which your project is missing ⛔. Please go ahead and add the missing section to your project 📝.

**About myself section:**
![image](https://user-images.githubusercontent.com/43172164/198828296-bff1f8a4-f9ba-4f2a-8043-8de92f57ad95.png)

2022-10-30 14:14 UTC, posh101 commented
Hello, I have actually completed the Hello Microverse project and the
Mobile First project. It has been approved.
Please why do I have to repeat it?

On Sat, 29 Oct 2022 at 12:19, Yasin Warsame ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hi @posh101 <https://github.com/posh101>🖐🏾,
>
> You've done well implementing most of the project requirements 🎉, but
> there are still some changes you need to make before moving on to the next
> project 🔨.
> To highlight:
>
>    - Professional readme file ✔️
>    - Linters are passing ✔️
>
> STATUS: REQUIRED CHANGES ♻♻♻
>
> [image: ALMOST]
> <https://camo.githubusercontent.com/a09ee1857976f02153e07f6bffc2387333f951e50d53f99e54765ee73e00a8bc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f566c717a6561526e684376504c66725368362f67697068792e676966>
> *Check the comments under the review 👇🏽👇🏽👇🏽.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you take them into
> account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏 💻
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please ping me @Yazino12 <https://github.com/Yazino12> when you comment
> so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/posh101/My-Portfolio/pull/3#discussion_r1008678116>:
>
> > +        <br>
>
> +        <br>
>
> +        <br>
>
> +        <br>
>
> +        <br>
>
> +        <br>
>
> +        <br>
>
> +        <br>
>
> +        <br>
>
>
>
>    - *[OPTIONAL]* I see that you are using <br> tags to make the space
>    between your sections. To make your code clean try styling your section
>    margins, that way you are cleaning up these repeated lines of the same tag
>    and it will make your code much cleaner 🧹👊🏽.
>
> ------------------------------
>
> In index.html
> <https://github.com/posh101/My-Portfolio/pull/3#discussion_r1008680965>:
>
> > @@ -77,7 +69,47 @@ <h4 class="sub-title">I am a Software Developer</p>
>
>
>
>        </section>
>
>
>
> +      <section class="wrap">
>
> +        <br>
>
> +        <br>
>
> +        <br>
>
> +        <br>
>
> +        <br>
>
> +        <br>
>
> +        <br>
>
> +        <br>
>
> +        <br>
>
> +
>
>
>
>    -
>
>    Your projects section doesn't have the title *My Recent Works*. Please
>    add the title as you can see below your design has the title and your
>    project doesn't 👇🏽.
>    -
>
>    As in the design template the background of your card has a grayish
>    color. Kindly change the background to white 👍🏽.
>    -
>
>    *Your project*
>    [image: image]
>    <https://user-images.githubusercontent.com/43172164/198827205-17e90576-9767-4b8e-952a-09484738cc69.png>
>    -
>
>    *The design*
>    [image: image]
>    <https://user-images.githubusercontent.com/43172164/198827221-2e6e6b2e-af3b-497d-ae61-6a6289fc9bc3.png>
>
> ------------------------------
>
> In index.html
> <https://github.com/posh101/My-Portfolio/pull/3#discussion_r1008681245>:
>
> > +        <button class="button1" type="css">css</button>
>
> +        <button class="button2" type="html">html</button>
>
> +        <button class="button3" type="bootstrap">bootstrap</button>
>
> +        <button class="button4" type="Ruby">Ruby</button>
>
>
>
>    - For semantic correctness. HTML has the ability to express lists of
>    things, and it helps the Google robot 🤖, screen readers, and all
>    manner of users who don't care solely about the presentation of the site
>    understand your content better. For this reason, consider using li
>    nested with ul tags. So you end with something like this 👇🏽:
>
> [image: image]
> <https://user-images.githubusercontent.com/43172164/198827727-f621e468-0cb6-4f3e-a633-ff09ae20951d.png>
> ------------------------------
>
> In index.html
> <https://github.com/posh101/My-Portfolio/pull/3#discussion_r1008681591>:
>
> > +    <p class="text">
>
> +        A daily selection of privately
>
> +         personalized reads; no accounts or
>
> +          sign-ups required. has been the
>
> +           industry's standard dummy text ever
>
> +           since the 1500s, when an unknown
>
> +           printer took a standard dummy text.
>
> +    </p>
>
> +    </div>
>
> +
>
> +    <nav class="button">
>
> +        <button class="button1" type="css">css</button>
>
> +        <button class="button2" type="html">html</button>
>
> +        <button class="button3" type="bootstrap">bootstrap</button>
>
> +        <button class="button4" type="Ruby">Ruby</button>
>
> +        <button class="button5" type="See Project">See Project</button>
>
>
>
>    - Having elements that load quickly while displaying a simple
>    interface, consider adding button styling: Active, Hover, and Pressed to
>    your button ✨. see design
>    <https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122>
>
> ------------------------------
>
> In index.html
> <https://github.com/posh101/My-Portfolio/pull/3#discussion_r1008682848>:
>
> > +    </nav>
>
> +
>
> +    </section>
>
> +    </section>
>
> +
>
>      </main>
>
> +
>
>
>
>  </body>
>
>  </html>
>
>
>
>    - As in the project requirement
>    <https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md>
>    you were expected to implement two sections: *The projects* section
>    which you implemented ✔ and the *About myself* section which your
>    project is missing ⛔. Please go ahead and add the missing section to
>    your project 📝.
>
> *About myself section:*
> [image: image]
> <https://user-images.githubusercontent.com/43172164/198828296-bff1f8a4-f9ba-4f2a-8043-8de92f57ad95.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/posh101/My-Portfolio/pull/3#pullrequestreview-1160962574>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZ6TTE4P7OCX7WLAOWYXPSLWFUB3BANCNFSM6AAAAAARRXFA3I>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-02 08:32 UTC, merged