My first mobile app
posh101/My-Portfolio pull request #5
Opened 2022-11-03 14:23 UTC by posh101

## Best Portfolio

- Built with HTML, CSS, and GitHub
- I created a new branch
- I add HTML, CSS, and linters
- The portfolio has 11 different sections but with HTML and styled with CSS.
- I also added a readme file.

2022-11-03 15:37 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @posh101, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

-   No linter errors. :heavy_check_mark: 
-   Correct GitHub Flow. :heavy_check_mark: 
-   Good README file. :heavy_check_mark: 

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [ ] Kindly replace the text `menu` on your navbar with hamburger icon as to be in line with what's on the guiding template.

### Your Design

![hamburger-position](https://user-images.githubusercontent.com/26597432/199765210-03f27bb3-2777-4a01-93a2-a8fce0398bc8.png)


### Figma Design

![temp-hamburger](https://user-images.githubusercontent.com/26597432/199765319-6794fec8-daaf-45a5-b33b-3f225290d71c.png)


- [ ] Two of your social icons on the headline part of your project is not showing correct. You may need to consider checking what's the issue.

![social-icons](https://user-images.githubusercontent.com/26597432/199765759-e8f97acd-3865-45b4-ad47-c38f1faec439.png)

2022-11-03 15:37 UTC, Qoosim commented on index.html
> +    </header>
- [ ] Kindly reduce the font-size of your `h1` for it to be in line with the given template.

### Your Design

![your-about-me](https://user-images.githubusercontent.com/26597432/199761655-8907c5e7-52d9-48ca-b3df-51d3dcee1051.png)


### Figma Design

![temp-about-me](https://user-images.githubusercontent.com/26597432/199761721-c0c61460-e5a5-4960-a6f9-8c33adf65db5.png)

2022-11-03 15:37 UTC, Qoosim commented on index.html
> +        <div class="see122">See Project</div>
- [ ] Kindly position this div and give it appropriate color like what is on the guiding template. It is not properly positioned at this moment.

![button-reposition](https://user-images.githubusercontent.com/26597432/199763870-a08fc880-410b-4bf6-9807-a7b3e804c467.png)


- [ ] Kindly make the div and link or better still change it to `button` for semantic reason.

2022-11-03 15:37 UTC, Qoosim commented on index.html
> +      <div class="get">Get My Resume</div>
- [ ] Kindly make this div a link or better still a button for semantic reason.

2022-11-03 20:47 UTC, Owusu-Desmond approved these changes
Hi @posh101  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set up the project ✅
📌 Good commit messages.

## Optional suggestions

- [ OPTIONAL ] Your readme file is not professional. Please would be better to make your readme file professional since it is the first impression if someone visit to project here. Please make sure you follow [Microverse README template](https://github.com/microverseinc/readme-template/blob/master/README.md) :pray: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 22:01 UTC, merged

2022-11-05 14:27 UTC, posh101 commented
Hello

Please i have finished my quiz and submitted but it has not reflected on my
dashboard and I have not seen my scores.

On Thu, 3 Nov 2022 at 21:47, Desmond Owusu Ansah ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @posh101 <https://github.com/posh101> ,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> <https://camo.githubusercontent.com/41b126df3eea8ea04ec838420a63de0758964c3695ef0e445e98fbb8e7bb0ec8/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966>
> Highlights
>
> 📌 No Linters error ✅
> 📌 Descriptive pull request✅
> 📌 Great working on the set up the project ✅
> 📌 Good commit messages.
> Optional suggestions
>
>    - [ OPTIONAL ] Your readme file is not professional. Please would be
>    better to make your readme file professional since it is the first
>    impression if someone visit to project here. Please make sure you follow Microverse
>    README template
>    <https://github.com/microverseinc/readme-template/blob/master/README.md>
>    🙏
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/posh101/My-Portfolio/pull/5#pullrequestreview-1167642733>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZ6TTE4BG3OXA7V2LGPMSXTWGQQF3ANCNFSM6AAAAAARWGFIKE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>